import {
  FaBeer,
  FaCocktail,
  FaCoffee,
  FaIceCream,
  FaLeaf,
  FaUtensils,
  FaWineGlass,
} from "react-icons/fa";

// Sincronizado com https://cowboybeer.cloudfy.net.br/home em 31/07/2026.
export const menuCategories = [
  {
    id: "laut",
    title: "LAUT",
    icon: FaBeer,
    items: [
      { name: "LAUT VENM DRINK LATA 355ML", price: "R$ 10,00", desc: "", photo: "/cardapio/oficial/laut-venm-drink-lata-355ml.webp" },
      { name: "LAUT LIKE SPRITZ LATA 355ML", price: "R$ 20,00", desc: "", photo: "/cardapio/oficial/laut-like-spritz-lata-355ml.webp" },
      { name: "CHOPP DE LEVE LAUT 355ML", price: "R$ 12,99", desc: "", photo: "/cardapio/oficial/chopp-de-leve-laut-355ml.webp" },
      { name: "CHOPP PALE ALE LAUT 355ML", price: "R$ 14,99", desc: "", photo: "/cardapio/oficial/chopp-pale-ale-laut-355ml.webp" },
      { name: "CHOPP PILSEN LAUT 355ML", price: "R$ 12,99", desc: "", photo: "/cardapio/oficial/chopp-pilsen-laut-355ml.webp" },
      { name: "CHOPP SESSION IPA LAUT 355ML", price: "R$ 14,99", desc: "", photo: "/cardapio/oficial/chopp-session-ipa-laut-355ml.webp" },
      { name: "CERVEJA LAUT PILSEN LONG NECK 355ML", price: "R$ 10,00", desc: "", photo: "/cardapio/oficial/cerveja-laut-pilsen-long-neck-355ml.webp" },
      { name: "CERVEJA LAUT PILSEN 600ML", price: "R$ 13,99", desc: "", photo: "/cardapio/oficial/cerveja-laut-pilsen-600ml.webp" },
      { name: "CERVEJA LAUT PILSEN LATA 473ML", price: "R$ 7,00", desc: "", photo: "/cardapio/oficial/cerveja-laut-pilsen-lata-473ml.webp" },
      { name: "CERVEJA LAUT DE LEVE 600ML", price: "R$ 13,99", desc: "", photo: "/cardapio/oficial/cerveja-laut-de-leve-600ml.webp" },
      { name: "CERVEJA LAUT DE LEVE LONG NECK 355ML", price: "R$ 10,00", desc: "", photo: "/cardapio/oficial/cerveja-laut-de-leve-long-neck-355ml.webp" },
      { name: "CERVEJA LAUT DOUBLE IPA 600ML", price: "R$ 24,99", desc: "", photo: "/cardapio/oficial/cerveja-laut-double-ipa-600ml.webp" },
      { name: "CERVEJA LAUT AMBAR LAGER 600ML", price: "R$ 17,99", desc: "", photo: "/cardapio/oficial/cerveja-laut-ambar-lager-600ml.webp" },
      { name: "CERVEJA LAUT AMERICAN IPA 600ML", price: "R$ 22,99", desc: "", photo: "/cardapio/oficial/cerveja-laut-american-ipa-600ml.webp" },
      { name: "CERVEJA LAUT DARK LARGER 600ML", price: "R$ 18,99", desc: "", photo: "/cardapio/oficial/cerveja-laut-dark-larger-600ml.webp" },
      { name: "CERVEJA LAUT MEIDIA 600ML", price: "R$ 17,99", desc: "", photo: "/cardapio/oficial/cerveja-laut-meidia-600ml.webp" },
      { name: "CERVEJA LAUT SESSION IPA 600ML", price: "R$ 19,99", desc: "", photo: "/cardapio/oficial/cerveja-laut-session-ipa-600ml.webp" },
      { name: "LIKE WINE RIO 0,0% 269ML", price: "R$ 20,00", desc: "", photo: "/cardapio/oficial/like-wine-rio-0-0-269ml.webp" },
      { name: "LIKE WINE ISTAMBUL MOSCATEL BRANCO 269ML", price: "R$ 20,00", desc: "", photo: "/cardapio/oficial/like-wine-istambul-moscatel-branco-269ml.webp" },
      { name: "LIKE WINE VEGAS MOSCATEL ROSE 269ML", price: "R$ 20,00", desc: "", photo: "/cardapio/oficial/like-wine-vegas-moscatel-rose-269ml.webp" },
      { name: "LIKE WINE IBIZA BRUT BRANCO 269ML", price: "R$ 20,00", desc: "", photo: "/cardapio/oficial/like-wine-ibiza-brut-branco-269ml.webp" },
      { name: "LIKE WINE TOKYO BRUT ROSE 269ML", price: "R$ 20,00", desc: "", photo: "/cardapio/oficial/like-wine-tokyo-brut-rose-269ml.webp" },
      { name: "JIMMY NEGRONI GARRAFA 750 ML", price: "R$ 180,00", desc: "", photo: "/cardapio/oficial/jimmy-negroni-garrafa-750-ml.webp" },
      { name: "JIMMY GIN LONDON DRY GARRAFA 750 ML", price: "R$ 99,00", desc: "", photo: "/cardapio/oficial/jimmy-gin-london-dry-garrafa-750-ml.webp" },
      { name: "JIMMY VODKA GARRAFA 900 ML", price: "R$ 89,00", desc: "", photo: "/cardapio/oficial/jimmy-vodka-garrafa-900-ml.webp" },
    ],
  },
  {
    id: "cervejas",
    title: "Cervejas e Chopp Gelado",
    icon: FaBeer,
    items: [
      { name: "Amstel 600ml", price: "R$ 14,99", desc: "", photo: "/cardapio/cervejasechop/amstel-600ml.webp" },
      { name: "Amstel Long Neck", price: "R$ 8,99", desc: "", photo: "/cardapio/cervejasechop/amstel-long-neck.webp" },
      { name: "Amstel Ultra Long Neck", price: "R$ 11,99", desc: "", photo: "/cardapio/cervejasechop/amstel-ultra-long-neck.webp" },
      { name: "Antartica Boa 600ml", price: "R$ 14,99", desc: "", photo: "/cardapio/cervejasechop/antarctica-boa-600ml.webp" },
      { name: "Baden Baden Pilsen 600ml", price: "R$ 21,90", desc: "", photo: "/cardapio/oficial/baden-baden-pilsen-600ml.webp" },
      {
        name: "Chapéu do Cowboy",
        price: "R$ 35,90",
        desc: "Cozumel exclusivo do Cowboy Beer com limão, gelo, borda de sal e cerveja 600ml",
        photo: "/cardapio/cervejasechop/chapeu-do-cowboy.webp",
      },
      { name: "Chop Kaiser 355ml", price: "R$ 17,99", desc: "", photo: "/cardapio/cervejasechop/chop-kaiser-355ml.webp" },
      { name: "Corona 600ml", price: "R$ 19,90", desc: "", photo: "/cardapio/cervejasechop/corona-600ml.webp" },
      { name: "Corona Extra Long Neck", price: "R$ 11,99", desc: "", photo: "/cardapio/cervejasechop/corona-extra-long-neck.webp" },
      { name: "Eisenbahn Pilsen Long Neck", price: "R$ 9,99", desc: "", photo: "/cardapio/cervejasechop/eisenbahn-pilsen-long-neck.webp" },
      { name: "Eisenbahn IPA Long Neck", price: "R$ 9,99", desc: "", photo: "/cardapio/cervejasechop/eisenbahn-ipa-long-neck.webp" },
      { name: "Estrella Galicia Long Neck", price: "R$ 9,99", desc: "", photo: "/cardapio/oficial/estrella-galicia-long-neck.webp" },
      { name: "Estrella Galicia Zero Long Neck", price: "R$ 9,99", desc: "", photo: "/cardapio/oficial/estrella-galicia-zero-long-neck.webp" },
      { name: "Promoção Estrella Galicia Lager 600ml", price: "R$ 9,99", desc: "", photo: "/cardapio/oficial/promocao-estrella-galicia-lager-600ml.webp" },
      { name: "Heineken 600ml", price: "R$ 18,99", desc: "", photo: "/cardapio/cervejasechop/heineken-600ml.webp" },
      { name: "Heineken Long Neck", price: "R$ 11,99", desc: "", photo: "/cardapio/cervejasechop/heineken-long-neck.webp" },
      { name: "Heineken Long Neck Zero", price: "R$ 11,99", desc: "", photo: "/cardapio/cervejasechop/heineken-long-neck-zero.webp" },
      { name: "Original 600ml", price: "R$ 17,99", desc: "", photo: "/cardapio/cervejasechop/original-600ml.webp" },
      { name: "Praya Long Neck", price: "R$ 11,99", desc: "", photo: "/cardapio/cervejasechop/praya-long-neck.webp" },
      { name: "Sol Long Neck", price: "R$ 11,99", desc: "", photo: "/cardapio/cervejasechop/sol-long-neck.webp" },
      { name: "Stella Artois Pure Gold Long Neck", price: "R$ 11,99", desc: "", photo: "/cardapio/cervejasechop/stella-artois-pure-gold-long-neck.webp" },
      { name: "Stella Artois Pure Gold 600ml", price: "R$ 19,90", desc: "", photo: "/cardapio/oficial/stella-artois-pure-gold-600ml.webp" },
    ],
  },
  {
    id: "porcoes-saladas",
    title: "Porções e Saladas do Cowboy",
    icon: FaUtensils,
    items: [
      {
        name: "Batata Costela e Cheddar",
        price: "R$ 46,90",
        desc: "Batata palito e deliciosa costela desfiada coberta com molho cheddar",
        photo: "/cardapio/porcaoesalada/batata-costela-e-cheddar.webp",
      },
      {
        name: "Caesar Salad",
        price: "R$ 32,00",
        desc: "Alface romana com cubos de frango, croutons, lascas de parmesão e molho caesar",
        photo: "/cardapio/porcaoesalada/caesar-salad.webp",
      },
      { name: "Contra Filé na Chapa", price: "R$ 74,90", desc: "", photo: "/cardapio/oficial/contra-file-na-chapa.webp" },
      {
        name: "Fígado Acebolado com Jiló",
        price: "R$ 44,90",
        desc: "Acompanha farofa de ovo",
        photo: "/cardapio/porcaoesalada/figado-acebolado-com-jilo.webp",
      },
      {
        name: "Frios do Arizona",
        price: "R$ 69,90",
        desc: "Tábua de frios (azeitona, palmito, salaminho, queijo artesanal e gouda, pepperoni, geleia especial, amendoim, torradinhas e frutas da estação)",
        photo: "/cardapio/porcaoesalada/frios-do-arizona.webp",
      },
      {
        name: "John Wesley Pistoleiro",
        price: "R$ 44,90",
        desc: "Calabresa acebolada acompanhada de batatas rústicas e molho do chef",
        photo: "/cardapio/porcaoesalada/john-wesley-pistoleiro.webp",
      },
      {
        name: "Mexidão do Chef",
        price: "R$ 32,00",
        desc: "Deliciosa mistura de arroz, feijão, ovo mole, couve, carne assada e banana frita",
        photo: "/cardapio/porcaoesalada/mexidao-do-chef.webp",
      },
      {
        name: "Montaria Frie",
        price: "R$ 52,00",
        desc: "Batata palito, bacon e cheddar",
        photo: "/cardapio/porcaoesalada/montaria-frie.webp",
      },
      {
        name: "Parmegiana de Frango",
        price: "R$ 45,90",
        desc: "Parmegiana de frango com muito queijo",
        photo: "/cardapio/porcaoesalada/parmegianafrango.webp",
      },
      {
        name: "Queijo Artesanal Temperadinho",
        price: "R$ 24,90",
        desc: "Cubos de queijo com tempero da roça",
        photo: "/cardapio/porcaoesalada/queijo-artesanal-temperadinho.webp",
      },
      {
        name: "Salada de Jiló",
        price: "R$ 22,90",
        desc: "Rodelas de jiló com tempero especial da casa",
        photo: "/cardapio/porcaoesalada/salada-de-jilo.webp",
      },
      { name: "Tirinhas Filé de Tilápia (Fish and)", price: "R$ 64,90", desc: "", photo: "/cardapio/oficial/tirinhas-file-de-tilapia-fish-and.webp" },
      { name: "Torresmo (Duelo)", price: "R$ 58,00", desc: "", photo: "/cardapio/oficial/torresmo-duelo.webp" },
      {
        name: "White Ceviche",
        price: "R$ 48,00",
        desc: "Cubos de tilápia, cebola roxa, pimenta dedo-de-moça, limão e coentro",
        photo: "/cardapio/porcaoesalada/white-ceviche.webp",
      },
    ],
  },
  {
    id: "extras",
    title: "Extras",
    icon: FaUtensils,
    items: [
      { name: "Vinagrete", price: "R$ 10,00", desc: "", photo: "/cardapio/extras/vinagrete.webp" },
    ],
  },
  {
    id: "bebidas-nao-alcoolicas",
    title: "Água, Refri e Energético",
    icon: FaCoffee,
    items: [
      { name: "Água com Gás", price: "R$ 5,50", desc: "", photo: "/cardapio/bebidasemais/aguacomgas.webp" },
      { name: "Água sem Gás", price: "R$ 5,00", desc: "", photo: "/cardapio/bebidasemais/aguasemgas.webp" },
      { name: "Água de Coco", price: "R$ 7,00", desc: "", photo: "/cardapio/bebidasemais/aguadecoco.webp" },
      { name: "Coca Cola 310ml", price: "R$ 7,00", desc: "Sabores: original e zero", photo: "/cardapio/bebidasemais/cocacola310ml.webp" },
      { name: "Fanta 310ml", price: "R$ 7,00", desc: "Sabores: guaraná, guaraná zero, laranja e uva", photo: "/cardapio/bebidasemais/fanta310ml.webp" },
      { name: "FYS Água Tônica 350ml", price: "R$ 5,00", desc: "", photo: "/cardapio/bebidasemais/fys350ml.webp" },
      { name: "FYS 350ml", price: "R$ 5,00", desc: "Sabores: guaraná da Amazônia e limão siciliano", photo: "/cardapio/bebidasemais/fys350ml.webp" },
      { name: "Sprite 310ml", price: "R$ 6,00", desc: "Sabores: limão tradicional e zero", photo: "/cardapio/bebidasemais/sprite310ml.webp" },
      { name: "Sprite Lemon 510ml", price: "R$ 7,00", desc: "", photo: "/cardapio/bebidasemais/spritelemon510ml.webp" },
      { name: "Schweppes Água Tônica 310ml", price: "R$ 7,00", desc: "", photo: "/cardapio/bebidasemais/schweppesaguatonica310ml.webp" },
      { name: "Schweppes Citrus 310ml", price: "R$ 7,00", desc: "", photo: "/cardapio/bebidasemais/schweppescitrus310ml.webp" },
      { name: "Monster Energy", price: "R$ 15,00", desc: "Consulte os sabores com o garçom", photo: "/cardapio/bebidasemais/monsterenergy.webp" },
      { name: "Red Bull", price: "R$ 16,00", desc: "Consulte os sabores com o garçom", photo: "/cardapio/bebidasemais/redbull.webp" },
    ],
  },
  {
    id: "bebidas-naturais",
    title: "Suco Natural 400ml e Del Valle",
    icon: FaLeaf,
    items: [
      { name: "2 Sabores", price: "R$ 15,90", desc: "Consulte os sabores disponíveis com o garçom", photo: "/cardapio/bebidanatural/doissabores.webp" },
      { name: "Ao Leite", price: "R$ 17,90", desc: "Consulte os sabores disponíveis com o garçom", photo: "/cardapio/bebidanatural/aoleite.webp" },
      { name: "Da Fruta", price: "R$ 12,90", desc: "Sabores: abacaxi, abacaxi com hortelã, acerola, laranja, limão, limonada suíça, maracujá, morango e tamarindo", photo: "/cardapio/bebidanatural/dafruta.webp" },
      { name: "Del Valle", price: "R$ 7,00", desc: "Sabores: goiaba, manga, maracujá, pêssego e uva", photo: "/cardapio/bebidasemais/delvalle.webp" },
      { name: "Frutas Vermelhas", price: "R$ 20,90", desc: "", photo: "/cardapio/bebidanatural/frutasvermelhas.webp" },
      { name: "Laranja com Acerola", price: "R$ 15,90", desc: "", photo: "/cardapio/oficial/laranja-com-acerola.webp" },
    ],
  },
  {
    id: "caipirinhas",
    title: "Caipirinhas e Caipivodkas",
    icon: FaCocktail,
    items: [
      {
        name: "Caipirinha 2 Sabores",
        price: "R$ 27,90",
        desc: "Faça a combinação do seu gosto!",
        photo: "/cardapio/caipvodkacaipirinha/doissaborescaipirinha.webp",
      },
      { name: "Caipirinha Limão", price: "R$ 25,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipirinhalimao.webp" },
      { name: "Caipirinha Maracujá", price: "R$ 25,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipirinhamaracuja.webp" },
      { name: "Caipirinha Morango", price: "R$ 25,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipirinhamorango.webp" },
      {
        name: "Caipirinha Outros Sabores",
        price: "R$ 26,90",
        desc: "Sabores da estação. Consulte a disponibilidade com o garçom.",
        photo: "/cardapio/caipvodkacaipirinha/caipirinhaoutrossabores.webp",
      },
      {
        name: "Caipirinha Sagatiba",
        price: "R$ 27,90",
        desc: "O sabor é a sua escolha.",
        photo: "/cardapio/caipvodkacaipirinha/caipirinhasagatiba.webp",
      },
      { name: "Caipirinha Tamarindo", price: "R$ 25,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipirinhatamarindo.webp" },
      { name: "Caipirinha Velho Oeste", price: "R$ 26,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipirinhavelhoooeste.webp" },
      { name: "Caipivodka Limão", price: "R$ 26,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipivodkalimao.webp" },
      { name: "Caipivodka Maracujá", price: "R$ 25,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipivodkamaracuja.webp" },
      { name: "Caipivodka Maracujá Importado", price: "R$ 26,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipivodkamaracujaimportado.webp" },
      { name: "Caipivodka Morango", price: "R$ 25,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipivodkamorango.webp" },
      { name: "Caipivodka Morango Importado", price: "R$ 26,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipivodkamorangoimportado.webp" },
      { name: "Caipivodka Tamarindo", price: "R$ 25,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipivodkatamarindo.webp" },
      { name: "Caipivodka Tamarindo Importado", price: "R$ 26,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipivodkatamarindoimportada.webp" },
      { name: "Caipivodka Velho Oeste", price: "R$ 26,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipivodkavelhooeste.webp" },
      { name: "Caipivodka Velho Oeste Importado", price: "R$ 27,90", desc: "", photo: "/cardapio/caipvodkacaipirinha/caipivodkavelhooesteimportado.webp" },
    ],
  },
  {
    id: "drinks-cowboy",
    title: "Drinks Autorais Cowboy Beer",
    icon: FaCocktail,
    items: [
      { name: "8 Segundos", price: "R$ 29,90", desc: "Johnnie Walker Red, gelo e suco de limão", photo: "/cardapio/drinkscowboy/8segundos.webp" },
      { name: "Boate Azul", price: "R$ 34,90", desc: "Gin, xarope de violeta e suco de limão", photo: "/cardapio/oficial/boate-azul.webp" },
      { name: "Bourbon Honey", price: "R$ 39,90", desc: "Whisky bourbon, limão siciliano, xarope de gengibre, Cointreau, Angostura, espuma cítrica e mel", photo: "/cardapio/drinkscowboy/bourbonhoney.webp" },
      { name: "Bull Village", price: "R$ 42,90", desc: "Ballena, Leche Loko, morango e licor de café", photo: "/cardapio/drinkscowboy/bullvillage.webp" },
      { name: "Canarinho", price: "R$ 22,00", desc: "Kiwi, água tônica e Montila", photo: "/cardapio/oficial/canarinho.webp" },
      { name: "Drink da Patroa", price: "R$ 28,90", desc: "Pinga, suco de limão, gengibre e especiarias", photo: "/cardapio/drinkscowboy/drinkdapatroa.webp" },
      { name: "Drink do Cowboy", price: "R$ 28,90", desc: "Pinga, suco de limão, xarope de kiwi e especiarias", photo: "/cardapio/drinkscowboy/drinkdocowboy.webp" },
      { name: "Drink Paraíso Tropical", price: "R$ 39,90", desc: "Vodka, maracujá, abacaxi e laranja", photo: "/cardapio/drinkscowboy/drinkparaisotropical.webp" },
      { name: "Drink Sola da Bota", price: "R$ 39,90", desc: "Licor 43, Amarula e licor de café", photo: "/cardapio/drinkscowboy/drinksoladabota.webp" },
      { name: "Faroeste", price: "R$ 39,90", desc: "Geleia de frutas vermelhas, limão siciliano, mix de vodka e gin com espuma cítrica", photo: "/cardapio/drinkscowboy/faroeste.webp" },
      { name: "Fivela de Prata", price: "R$ 34,90", desc: "Baileys, café, vodka e gelo", photo: "/cardapio/drinkscowboy/fiveladeprata.webp" },
      { name: "Made in Roça", price: "R$ 34,90", desc: "Whisky bourbon, maracujá, limão, mel e raspas de rapadura", photo: "/cardapio/drinkscowboy/madeinroca.webp" },
      { name: "Maracountry Drink", price: "R$ 39,90", desc: "Pinga 51, maracujá, limão e leite condensado", photo: "/cardapio/drinkscowboy/maracountrydrink.webp" },
      { name: "Mississipi", price: "R$ 39,90", desc: "Vinho tinto infusionado na cereja, whisky bourbon, xarope de limão siciliano e Angostura", photo: "/cardapio/drinkscowboy/mississipi.webp" },
      { name: "Novo Mundo", price: "R$ 36,90", desc: "Abacaxi, hortelã, cachaça branca, suco de caju, suco de limão e xarope de gengibre", photo: "/cardapio/drinkscowboy/novomundo.webp" },
      { name: "Passion Country", price: "R$ 36,90", desc: "Cachaça, morango, Licor 43, maracujá, xarope de açúcar e Angostura", photo: "/cardapio/drinkscowboy/passioncountry.webp" },
      { name: "Rodeio", price: "R$ 42,90", desc: "Whisky, Malibu, limão, Amaretto, Limoncello e chopp", photo: "/cardapio/drinkscowboy/rodeio.webp" },
      { name: "Sal e Toranja Nashville", price: "R$ 28,90", desc: "Abacaxi, hortelã, cachaça branca, suco de caju, suco de limão e xarope de gengibre", photo: "/cardapio/drinkscowboy/saletoranjanashville.webp" },
      { name: "Talismã", price: "R$ 22,00", desc: "Rum, água tônica e tangerina", photo: "/cardapio/drinkscowboy/talisma.webp" },
      { name: "Tentação Selvagem Drink", price: "R$ 28,90", desc: "Licor de chocolate, maracujá e energético", photo: "/cardapio/drinkscowboy/talisma.webp" },
    ],
  },
  {
    id: "drinks-classicos",
    title: "Drinks Clássicos",
    icon: FaCocktail,
    items: [
      { name: "Aperol", price: "R$ 33,90", desc: "Aperol, água com gás e prosecco", photo: "/cardapio/drinkclassico/aperol.webp" },
      { name: "Boulevardier", price: "R$ 48,90", desc: "Campari, whisky bourbon e limão desidratado", photo: "/cardapio/drinkclassico/boulevardie.webp" },
      { name: "Cosmopolitan", price: "R$ 31,90", desc: "Vodka, cranberry, triple sec e suco de limão", photo: "/cardapio/drinkclassico/cosmopolitan.webp" },
      { name: "Fitzgerald", price: "R$ 29,90", desc: "Gin, suco de limão siciliano, xarope de açúcar e Angostura", photo: "/cardapio/drinkclassico/fitzgerald.webp" },
      { name: "Margarita", price: "R$ 32,90", desc: "Cointreau, limão, tequila e açúcar", photo: "/cardapio/drinkclassico/margarita.webp" },
      { name: "Mojito", price: "R$ 28,90", desc: "Rum, limão, hortelã e água com gás", photo: "/cardapio/drinkclassico/mojito.webp" },
      { name: "Moscow Mule", price: "R$ 29,90", desc: "Vodka, mix de gengibre e limão com espuma de gengibre", photo: "/cardapio/drinkclassico/moscowmule.webp" },
      { name: "Negroni", price: "R$ 48,00", desc: "Gin, Campari, vermouth e casca de laranja", photo: "/cardapio/drinkclassico/negroni.webp" },
      { name: "Pina Colada", price: "R$ 34,90", desc: "Abacaxi, leite condensado, rum, creme de coco e cereja", photo: "/cardapio/drinkclassico/pinadcolada.webp" },
    ],
  },
  {
    id: "sem-alcool",
    title: "Drinks sem Álcool",
    icon: FaCocktail,
    items: [
      {
        name: "Shake do Cowboy Frutas Vermelhas",
        price: "R$ 18,90",
        desc: "Frutas vermelhas, leite condensado, milk e calda de chocolate ou morango",
        photo: "/cardapio/semalcool/shakedocowboymorango.webp",
      },
      {
        name: "Shake do Cowboy Maracujá",
        price: "R$ 18,90",
        desc: "Maracujá, leite condensado, milk e calda de chocolate ou morango",
        photo: "/cardapio/semalcool/shakedocowboymorango.webp",
      },
      {
        name: "Shake do Cowboy Morango",
        price: "R$ 18,90",
        desc: "Morango, leite condensado, milk e calda de chocolate ou morango",
        photo: "/cardapio/semalcool/shakedocowboymorango.webp",
      },
      { name: "Soda Italiana", price: "R$ 14,90", desc: "Consulte os sabores disponíveis com o garçom", photo: "/cardapio/semalcool/sodaitaliana.webp" },
      { name: "Sonho de Boiadeira", price: "R$ 28,90", desc: "Purê de morango, maracujá, leite condensado e energético", photo: "/cardapio/semalcool/sonhodeboiadeira.webp" },
    ],
  },
  {
    id: "spritz",
    title: "Spritz",
    icon: FaCocktail,
    items: [
      { name: "Aperol Spritz", price: "R$ 33,90", desc: "Aperol, água com gás e espumante", photo: "/cardapio/oficial/aperol-spritz.webp" },
      { name: "Campari Spritz", price: "R$ 33,90", desc: "Campari, água com gás e espumante", photo: "/cardapio/spritz/camparispritz.webp" },
      { name: "Limon Spritz", price: "R$ 36,90", desc: "Gin, soda, prosecco e Limoncello", photo: "/cardapio/oficial/limon-spritz.webp" },
    ],
  },
  {
    id: "campari-licor43",
    title: "Campari / Licor 43",
    icon: FaWineGlass,
    items: [
      { name: "43 Tropical", price: "R$ 39,90", desc: "Licor 43, energético tropical e polpa de maracujá", photo: "/cardapio/camparilicor43/43tropical.webp" },
      { name: "Camparinha", price: "R$ 27,90", desc: "Campari, cachaça, limão e açúcar", photo: "/cardapio/oficial/camparinha.webp" },
      { name: "Campari Tonic", price: "R$ 29,90", desc: "Campari, água tônica e rodela de laranja-baía", photo: "/cardapio/camparilicor43/camparitonic.webp" },
      { name: "Evidências Drink", price: "R$ 39,90", desc: "Licor 43, Amarula e licor de chocolate", photo: "/cardapio/camparilicor43/evidencias.webp" },
      { name: "Luxor 43", price: "R$ 39,90", desc: "Campari, Licor 43 e espumante", photo: "/cardapio/oficial/luxor-43.webp" },
    ],
  },
  {
    id: "batatas-recheadas",
    title: "Batatas Recheadas",
    icon: FaUtensils,
    items: [
      {
        name: "Frango",
        price: "R$ 25,00",
        desc: "Todas as batatas são recheadas com o molho secreto de queijo do chef",
        photo: "/cardapio/batatarecheada/batatarecheada.webp",
      },
      {
        name: "Queijo e Bacon",
        price: "R$ 25,00",
        desc: "Todas as batatas são recheadas com o molho secreto de queijo do chef",
        photo: "/cardapio/batatarecheada/batatarecheada.webp",
      },
      { name: "Strogronoff de Frango", price: "R$ 32,00", desc: "", photo: "/cardapio/batatarecheada/batatarecheada.webp" },
    ],
  },
  {
    id: "caldos",
    title: "Caldos 300ml",
    icon: FaUtensils,
    items: [
      { name: "Caldo de Frango", price: "R$ 28,90", desc: "", photo: "/cardapio/caldo300/caldodefrango.webp" },
      { name: "Caldo de Vaca Atolada", price: "R$ 24,90", desc: "", photo: "/cardapio/caldo300/caldodefrango.webp" },
    ],
  },
  {
    id: "massas",
    title: "Massas",
    icon: FaUtensils,
    items: [
      { name: "Espaguete Mac and Cheese", price: "R$ 25,90", desc: "Espaguete com queijo", photo: "/cardapio/massas/espaguetemacandcheese.webp" },
      { name: "Espaguete Meat Ball", price: "R$ 32,00", desc: "Espaguete com almôndegas ao molho vermelho da casa", photo: "/cardapio/massas/spaguetemeatball.webp" },
    ],
  },
  {
    id: "sanduiches-cowboy",
    title: "Sanduíches do Cowboy",
    icon: FaUtensils,
    items: [
      { name: "Buguer Chef", price: "R$ 36,50", desc: "Pão de hambúrguer, filé de frango empanado, cebola, alface, mussarela maçaricada e zucchini de abobrinha italiana", photo: "/cardapio/sanduichecowboy/burguerchef.webp" },
      { name: "Combo Cowboy", price: "R$ 42,90", desc: "Dallas Egg, batatas fritas e Coca Cola", photo: "/cardapio/sanduichecowboy/combocowboy.webp" },
      { name: "Dallas Egg", price: "R$ 28,00", desc: "Pão de hambúrguer, ovos, bacon, mussarela e molho rosé", photo: "/cardapio/sanduichecowboy/dallasegg.webp" },
      { name: "Especial Burguer", price: "R$ 39,90", desc: "Pão brioche com manteiga, alface, dois hambúrgueres, tomate, picles, cheddar e molho especial com bacon", photo: "/cardapio/sanduichecowboy/especialburguer.webp" },
      { name: "Regis Burguer", price: "R$ 36,00", desc: "Pão brioche, hambúrguer 100% Angus, cheddar, bacon, picles e maionese de páprica defumada", photo: "/cardapio/sanduichecowboy/regisburguer.webp" },
    ],
  },
  {
    id: "sobremesas",
    title: "Sobremesas",
    icon: FaIceCream,
    items: [
      { name: "Churros com Doce de Leite", price: "R$ 39,90", desc: "15 unidades", photo: "/cardapio/sobremesa/churros.webp" },
      { name: "Mousse de Maracujá", price: "R$ 12,90", desc: "", photo: "/cardapio/sobremesa/mousedemaracuja.webp" },
      { name: "Petit Gateau com Sorvete", price: "R$ 24,00", desc: "", photo: "/cardapio/sobremesa/petitgateau.webp" },
    ],
  },
];
